### ISSUE TITLE
Make research paper available

### ISSUE THREAD

**Issue by wetoo-cando** [RViMLab/vrviz#15]
Hello John,

Could you please make your paper "VRViz: Native VR Visualization of ROS Topics" available for reading?

Thanks a lot,
Rahul

**Comment by john-j-oneill** [comment]
No problem! The pdfs for both papers related to this work should be [here](https://github.com/RViMLab/vrviz/tree/master/vrviz/docs) now added in 1d60382d6b7b3d357d256f52eb32d8cad94e7fbb. Let me know if you have any questions about them.
Cheers,
John
