### ISSUE TITLE
Inverted VR display

### ISSUE THREAD

**Issue by utsavrai** [RViMLab/vrviz#16]
Launching vrviz.launch displays inverted view of headset also tf appears to be inverted as well
![vr_inverted](https://user-images.githubusercontent.com/25121619/108039834-a0b11d80-7062-11eb-9d95-9bd651ab528b.png)

**Comment by john-j-oneill** [comment]
Is this true in the actual headset as well? Or just in the preview window?
I've certainly had this happen in the preview window, although if I recall it doesn't always happen? I never got around to tracking it down, I don't use the preview window for much other than snooping on the headset user to help them if they get lost, so it wasn't terribly important to me.
I don't have my HMD with me currently so I can't do much testing, but let me know if it's happening in the headset too (That would be disorienting!) or if it's just in the preview I can take a look again and see if there's an obvious fix for it.

**Comment by john-j-oneill** [comment]
Hmm apparently I didn't try very hard to fix it, it looks pretty straightforward! I can't test it though, so any chance @utsavrai could try it out? The branch is on my fork here: https://github.com/john-j-oneill/vrviz/tree/inverted-companion-window-bug I haven't made a pull request yet because I want to get some confirmation that it works first. Thanks!

**Comment by utsavrai** [comment]
Yes it worked, thank you so much for such a quick reply. I would  just like to confirm one more thing with you, is it possible to integrate HTC Vive trackers with your package?

**Comment by john-j-oneill** [comment]
No problem, I'm just glad someone is making use of the project! 
It should be possible to use the Vive Trackers, I've never owned one, I ordered 2 while I was still at RViM and they got stuck in customs or something, I blame Brexit I guess... Anyways I think it should be easy to get their TF published back to ROS if that's what you mean, but I don't know about rendering them, the code to render the controllers came straight from the example code, I don't even know where those meshes live. I made a [branch](https://github.com/john-j-oneill/vrviz/tree/trackers) that should output them, with something like frame_depricated_X_Y. If that works let me know what X is and I can make it a friendlier name. Feel free to open an issue for that one too though!

**Comment by utsavrai** [comment]
Thanks a lot, I am able to get TF for htc vive trackers. You should update your description about supporting htc vive trackers too :). 

Thanks for such quick solutions, I really appreciate your work.

**Comment by john-j-oneill** [comment]
Hey, sorry to bug you @utsavrai but since I don't have a tracker, could you clarify, did the branch make them work? Or were they working all along? Thanks!

**Comment by utsavrai** [comment]
Yes branch made it work, previosly trackers were not detected.
 I wanted to ask one more thing, I was trying to project my screen on VR display [using](http://wiki.ros.org/screengrab_ros)  but since the vrviz_gl.cpp subscribes to image_transport and calculates the overlay orientation and width using camera intrinsic matrices, I am facing problem to just dispay image data that is published on a topic without any camera_info. Can you suggest anything on this?

**Comment by john-j-oneill** [comment]
Sorry for the delayed response! As for the raw image data it should subscribe to a raw image message just fine, or a full camera, The default topic it's looking for is `/rgb/image_raw` but you can remap that. That way you don't have to deal with the camera model and such (the camera model version is intended to render the image "in" the 3D scene, so it needs to know where the camera is mounted and such, but that code is commented out right now anyways, it came off kinda weird).

As for the dual eye thing, there's a param called `sbs_image` that should be what you want. Set it to false, and it will just put the same image to each eye. Sorry there's not any documentation of the params, that would certainly help! FYI the params are all loaded in [here ](https://github.com/RViMLab/vrviz/blob/master/vrviz/src/vrviz_gl.cpp#L2104) so you can at least trace them through the code. You may also want to tweak the hud_dist and hud_size variables as well, that scales how big the image appears.

**Comment by utsavrai** [comment]
Thank you so much and sorry for the late reply. Changing sbs_image param to false saved me from converting image into stereoscopic image :)
